version: '3.8'

services:
  node-staking-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dera-staking-service
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./src/abis:/app/src/abis:ro
    networks:
      - dera-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dera-network:
    driver: bridge
